// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeeklyPlanner.Infrastructure.Data;

#nullable disable

namespace WeeklyPlanner.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260302090908_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("WeeklyPlanner.Application.Models.BacklogItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("EstimatedHours")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.ToTable("BacklogItems");
                });

            modelBuilder.Entity("WeeklyPlanner.Application.Models.PlanningWeek", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ClientFocusedPct")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PlanningDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("RnDPct")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TechDebtPct")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PlanningWeeks");
                });

            modelBuilder.Entity("WeeklyPlanner.Application.Models.PlanningWeekMember", b =>
                {
                    b.Property<Guid>("PlanningWeekId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TeamMemberId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsReady")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlanningWeekId", "TeamMemberId");

                    b.HasIndex("TeamMemberId");

                    b.ToTable("PlanningWeekMembers");
                });

            modelBuilder.Entity("WeeklyPlanner.Application.Models.ProgressEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CompletedHours")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WorkItemId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkItemId");

                    b.ToTable("ProgressEntries");
                });

            modelBuilder.Entity("WeeklyPlanner.Application.Models.TeamMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TeamMembers");
                });

            modelBuilder.Entity("WeeklyPlanner.Application.Models.WorkItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BacklogItemId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CommittedHours")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompletedHours")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlanningWeekId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TeamMemberId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BacklogItemId");

                    b.HasIndex("TeamMemberId");

                    b.HasIndex("PlanningWeekId", "TeamMemberId");

                    b.ToTable("WorkItems");
                });

            modelBuilder.Entity("WeeklyPlanner.Application.Models.PlanningWeekMember", b =>
                {
                    b.HasOne("WeeklyPlanner.Application.Models.PlanningWeek", "PlanningWeek")
                        .WithMany("Members")
                        .HasForeignKey("PlanningWeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WeeklyPlanner.Application.Models.TeamMember", "TeamMember")
                        .WithMany("WeekMemberships")
                        .HasForeignKey("TeamMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanningWeek");

                    b.Navigation("TeamMember");
                });

            modelBuilder.Entity("WeeklyPlanner.Application.Models.ProgressEntry", b =>
                {
                    b.HasOne("WeeklyPlanner.Application.Models.WorkItem", "WorkItem")
                        .WithMany("ProgressEntries")
                        .HasForeignKey("WorkItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkItem");
                });

            modelBuilder.Entity("WeeklyPlanner.Application.Models.WorkItem", b =>
                {
                    b.HasOne("WeeklyPlanner.Application.Models.BacklogItem", "BacklogItem")
                        .WithMany("WorkItems")
                        .HasForeignKey("BacklogItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WeeklyPlanner.Application.Models.PlanningWeek", "PlanningWeek")
                        .WithMany("WorkItems")
                        .HasForeignKey("PlanningWeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WeeklyPlanner.Application.Models.TeamMember", "TeamMember")
                        .WithMany("WorkItems")
                        .HasForeignKey("TeamMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BacklogItem");

                    b.Navigation("PlanningWeek");

                    b.Navigation("TeamMember");
                });

            modelBuilder.Entity("WeeklyPlanner.Application.Models.BacklogItem", b =>
                {
                    b.Navigation("WorkItems");
                });

            modelBuilder.Entity("WeeklyPlanner.Application.Models.PlanningWeek", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("WorkItems");
                });

            modelBuilder.Entity("WeeklyPlanner.Application.Models.TeamMember", b =>
                {
                    b.Navigation("WeekMemberships");

                    b.Navigation("WorkItems");
                });

            modelBuilder.Entity("WeeklyPlanner.Application.Models.WorkItem", b =>
                {
                    b.Navigation("ProgressEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
